Handle EOF in recv_nonblocking
If recv_nonblocking is called and the ssh command ended with EOF
and empty output, the following error is produced because nbytes ==
SSS_EOF == -127:

```
File "src/pylibsshext/channel.pyx", line 112, in pylibsshext.channel.Channel.read_nonblocking
SystemError: Negative size passed to PyBytes_FromStringAndSize
```

It is better to handle it gracefully.